### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by eagleSIA** [LordYellow/sudoku#14]
https://github.com/LordYellow/sudoku/blob/c819c62b8d44aa3d7a0b27b023b67a42c2e316dc/header/gfield.h#L41
Maybe 100 isn't enough ?! this code is **not** safe :exclamation:

**Comment by eagleSIA** [comment]
#7

**Comment by yciam** [comment]
its better now, but i could be even more better

**Comment by yciam** [comment]
It is good enough now.
