### ISSUE TITLE
Dokumentation

### ISSUE THREAD

**Issue by eagleSIA** [LordYellow/sudoku#4]
Füge oben zu beginn jeder Datei folgendes hinzu:
`///@file <filename>`
Wobei `filename` natürlich der Name der jeweiligen Datei ist...

**Comment by eagleSIA** [comment]
Zudem sollte die dokumentation grundlegend erstellt werden... Im Anhang finden sich die nötigen beispiel dateien die lediglich funktionabel sind und modifiziert werden **sollten**...
Damit sie funktionieren muss die .txt endung entfernt werden... 

[footerFile.html.txt](https://github.com/LordYellow/sudoku/files/1954749/footerFile.html.txt)
[headerFile.html.txt](https://github.com/LordYellow/sudoku/files/1954755/headerFile.html.txt)
[styleSheetFile.css.txt](https://github.com/LordYellow/sudoku/files/1954754/styleSheetFile.css.txt)
[doxyfile.txt](https://github.com/LordYellow/sudoku/files/1954756/doxyfile.txt)

Sie müssen in den selben Ordner gepackt werden
Jetzt kann über `doxygen doxyfile` eine grundlegende dokumentation erstellt werden. 
Sie wird entweder über `firefox ./html/index.html` (firefox kann durch den benutzen browser ersetzt werden) oder über das manuelle aufrufen von ./html/index.html angezeigt werden. 

**Information:** es wurde doxygen 1.8.15 verwendet

**Comment by eagleSIA** [comment]
Wenn ein Fehler auftritt sollter auch mit `///@bug <desc> ` beschrieben werden.. 
Außerdem sollte eine ausführliche beschreibung vorliegen was bereits versuchst wurde bzw. woran er liegen könnte... am besten mit Bildern oder sudoku ausschnitten in diesem Fall damit eine schnelle nachvollziehbarkeit gewährleistet ist...

**Comment by yciam** [comment]
This will not be worked on.
