### ISSUE TITLE
Fehlersuche

### ISSUE THREAD

**Issue by eagleSIA** [LordYellow/sudoku#5]
- Es empfiehlt sich bei jedem aufruf von `getsolvedfield` zu überprüfen ob er das aktuelle sudoku bereits gesehen hat. 
- Wie wäre es eine log-datei zu erstellen in die das programm seine zwischenstände schreibt inklusive der Zahlen die es für ein bestimmtes feld für möglich hält. Diese kann man dann mit der bekannten Lösung des Sudokus abgleichen 
- die `oldfield = field` zuweisung in getsolvedfield scheint obsolet?
- Es empfhielt sich ein 9x9 array anstelle eines `vector<vector<int>> ` zu verwenden...
- Das verwenden von threads ist obsolet, da lediglich der mainthread ausgelagert wird, und nicht jeder einzelne lösungsversuch. 
- Man beachte die **rekursions-hölle**

**Comment by eagleSIA** [comment]
Zudem sollte man einmal überprüfen ob alle methoden wie removefromvector [camelCase oder_unterstrich] auch das tun was sie sollen... Dies ist **kein** direkter fehlerhinweis @LordYellow

**Comment by yciam** [comment]
1. Das Problem ist ja, dass dies geschieht. Eine ueberpruefung wuerde da j auch nichts bringen, oder sehe ich das Falsch?

2. Hab bereits getestet, ob die moeglichen Zahlen mit denen im geloesten Sudoku uebereinstimmen. Das ist immer der Fall.

3. Changed.

4. tbd

5. Der Grund dafuer is folgender: Die funktion die Ich rekusiv aufrufe sollte urspruenglich das geloeste field zurueck geben, aber ich wusste nicht, was ich zurueck geben sollte, wenn das feld nicht geloest wurde. Ich fand es einfacher es so wie jetzt umzusetzen, da so nichts zurueck gegeben werden muss.

6. Was ist das?

7. Ein Sudoku welches nach removeobvious geloest ist wurde korekt geloest. Da hier alle Methoden benutzt wurden gehe ich davon aus, dass diese Funktionieren

**Comment by eagleSIA** [comment]
- es geht hier nicht darum das problem zu lösen.. du musst es erstmal finden ... und da hilft es herauszufinden warum es das gleiche sudoku mehrfach betrachtet
- ok, wenn du das sagst
- zu 5) nicht gelöst = ursprüngliches sudoku
- zu 6) darin befindest du dich ^^^
- gefährliche annahme
