### ISSUE TITLE
Inefficient

### ISSUE THREAD

**Issue by eagleSIA** [LordYellow/sudoku#7]
https://github.com/LordYellow/sudoku/blob/24a8f20132300b1b12f2933929bbb2218fd24756/header/gfield.h#L65

This is inefficient, you just have to:
- get the amount of high-bits
- get a random high-bit

**Comment by yciam** [comment]
I dont get it.

**Comment by eagleSIA** [comment]
._. at least **try**
Wenns auf englisch nicht klappt mach ichs halt in Deutsch ^^. 
1. Mit der Funktion: 
```c++

  int countHighBits(int i) {
       i = i - ((i >> 1) & 0x55555555);
       i = (i & 0x33333333) + ((i >> 2) & 0x33333333);
       return (((i + (i >> 4)) & 0x0F0F0F0F) * 0x01010101) >> 24;
  }
  ```
2. Zählt man die Anzahl an gesetzten Bits in 32-Bit integer, das funktioniert demnach auch mit 16-Bit.
  Ein gesetzes Bit bedeuted bei dir ja, dass diese Zahl möglich ist!
3. Jetzt kannst du `uint8_t z = rand() % [amountOfHighBits];` ausführen. In deinem Fall: 
    `uint8_t z = rand() % countHighBits(field[i][a]);` Danut werden leere bits schon garnicht getroffen.
4. Jetzt musst du nur noch das Bit suchen welches das 'z-te' gesetze ist... Bei `0b1010` zum beispiel
    wäre `countHighBits()` 2 und wenn z nun 0 ist sollte deine methode 'getHighBit(uint8_t idx)' 1 
    zurückgeben, da sich das erste gesetze Bit an Position 1 (0-basiert) befindet. Dies lässt sich natürlich 
    mit dem zufälligen auswählen kombinieren und kompakter machen.
5. Damit ist die while schleife obsolet.
6. Siehe #8 für weitere möglichkeiten

**Comment by yciam** [comment]
I have done it in a different way.

**Comment by yciam** [comment]
Looks like my way was not good enough

**Comment by yciam** [comment]
done
