### ISSUE TITLE
Fix html output

### ISSUE THREAD

**Issue by eagleSIA** [LordYellow/sudoku#9]
https://github.com/LordYellow/sudoku/blob/24a8f20132300b1b12f2933929bbb2218fd24756/Doxyfile#L1120
you shouldn't change the basic style sheet file, as i said you should change the extra stylestheet.
Therefore Leave this line empty and change
https://github.com/LordYellow/sudoku/blob/24a8f20132300b1b12f2933929bbb2218fd24756/Doxyfile#L1133
to `HTML_EXTRA_STYLESHEET  = styleSheetFile`

**Comment by yciam** [comment]
done
